// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"
)

const activateDocument = `-- name: ActivateDocument :exec
UPDATE documents SET active = 1 WHERE id = ?
`

func (q *Queries) ActivateDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, activateDocument, id)
	return err
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (url, title, interval_days, next_review)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateDocumentParams struct {
	Url          string
	Title        string
	IntervalDays int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createDocument, arg.Url, arg.Title, arg.IntervalDays)
	return err
}

const deactivateDocument = `-- name: DeactivateDocument :exec
UPDATE documents SET active = 0 WHERE id = ?
`

func (q *Queries) DeactivateDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateDocument, id)
	return err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, url, title, interval_days, active, last_reviewed, next_review, review_count, created_at FROM documents WHERE id = ?
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.IntervalDays,
		&i.Active,
		&i.LastReviewed,
		&i.NextReview,
		&i.ReviewCount,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByURL = `-- name: GetDocumentByURL :one
SELECT id, url, title, interval_days, active, last_reviewed, next_review, review_count, created_at FROM documents WHERE url = ?
`

func (q *Queries) GetDocumentByURL(ctx context.Context, url string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByURL, url)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.IntervalDays,
		&i.Active,
		&i.LastReviewed,
		&i.NextReview,
		&i.ReviewCount,
		&i.CreatedAt,
	)
	return i, err
}

const incrementDocumentReviewCount = `-- name: IncrementDocumentReviewCount :exec
UPDATE documents SET review_count = review_count + 1 WHERE id = ?
`

func (q *Queries) IncrementDocumentReviewCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementDocumentReviewCount, id)
	return err
}

const listActiveDocuments = `-- name: ListActiveDocuments :many
SELECT id, url, title, interval_days, active, last_reviewed, next_review, review_count, created_at FROM documents WHERE active = 1
`

func (q *Queries) ListActiveDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.IntervalDays,
			&i.Active,
			&i.LastReviewed,
			&i.NextReview,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDocuments = `-- name: ListAllDocuments :many
SELECT id, url, title, interval_days, active, last_reviewed, next_review, review_count, created_at FROM documents
`

func (q *Queries) ListAllDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.IntervalDays,
			&i.Active,
			&i.LastReviewed,
			&i.NextReview,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDocuments = `-- name: ListDueDocuments :many
SELECT id, url, title, interval_days, active, last_reviewed, next_review, review_count, created_at FROM documents d
WHERE d.active = 1
  AND d.next_review <= CURRENT_TIMESTAMP
  AND NOT EXISTS (
    SELECT 1 FROM review_jobs rj
    WHERE rj.document_id = d.id AND rj.status = 'pending'
  )
`

func (q *Queries) ListDueDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDueDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.IntervalDays,
			&i.Active,
			&i.LastReviewed,
			&i.NextReview,
			&i.ReviewCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDocumentSchedule = `-- name: ResetDocumentSchedule :exec
UPDATE documents
SET last_reviewed = CURRENT_TIMESTAMP,
  next_review = DATETIME(CURRENT_TIMESTAMP, '+' || interval_days || ' days')
WHERE id = ?
`

func (q *Queries) ResetDocumentSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetDocumentSchedule, id)
	return err
}

const updateDocumentReview = `-- name: UpdateDocumentReview :exec
UPDATE documents
SET last_reviewed = CURRENT_TIMESTAMP,
  next_review = DATETIME(CURRENT_TIMESTAMP, '+' || interval_days || ' days'),
  review_count = review_count + 1
WHERE id = ?
`

func (q *Queries) UpdateDocumentReview(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDocumentReview, id)
	return err
}
