// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Document struct {
	ID           int64
	Url          string
	Title        string
	IntervalDays int64
	Active       bool
	LastReviewed sql.NullTime
	NextReview   sql.NullTime
	ReviewCount  int64
	CreatedAt    time.Time
}

type ReviewJob struct {
	ID          int64
	DocumentID  int64
	ReviewerID  int64
	Status      string
	AssignedAt  time.Time
	CompletedAt sql.NullTime
	ExpiresAt   sql.NullTime
	MessageID   sql.NullString
	Notes       sql.NullString
}

type Reviewer struct {
	ID            int64
	DiscordUserID string
	Username      string
	Active        bool
	LastAssigned  sql.NullTime
	CreatedAt     time.Time
}
