// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviewers.sql

package db

import (
	"context"
)

const activateReviewer = `-- name: ActivateReviewer :exec
UPDATE reviewers SET active = 1 WHERE id = ?
`

func (q *Queries) ActivateReviewer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, activateReviewer, id)
	return err
}

const createReviewer = `-- name: CreateReviewer :exec
INSERT INTO reviewers (discord_user_id, username)
VALUES (?, ?)
`

type CreateReviewerParams struct {
	DiscordUserID string
	Username      string
}

func (q *Queries) CreateReviewer(ctx context.Context, arg CreateReviewerParams) error {
	_, err := q.db.ExecContext(ctx, createReviewer, arg.DiscordUserID, arg.Username)
	return err
}

const deactivateReviewer = `-- name: DeactivateReviewer :exec
UPDATE reviewers SET active = 0 WHERE id = ?
`

func (q *Queries) DeactivateReviewer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateReviewer, id)
	return err
}

const deleteReviewer = `-- name: DeleteReviewer :exec
DELETE FROM reviewers WHERE id = ?
`

func (q *Queries) DeleteReviewer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReviewer, id)
	return err
}

const getLeastRecentReviewer = `-- name: GetLeastRecentReviewer :one
SELECT id, discord_user_id, username, active, last_assigned, created_at FROM reviewers
WHERE active = 1
  AND NOT EXISTS (
    SELECT 1 FROM review_jobs rj
    WHERE rj.reviewer_id = reviewers.id AND rj.status = 'pending'
  )
ORDER BY last_assigned ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetLeastRecentReviewer(ctx context.Context) (Reviewer, error) {
	row := q.db.QueryRowContext(ctx, getLeastRecentReviewer)
	var i Reviewer
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.Username,
		&i.Active,
		&i.LastAssigned,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewer = `-- name: GetReviewer :one
SELECT id, discord_user_id, username, active, last_assigned, created_at FROM reviewers WHERE id = ?
`

func (q *Queries) GetReviewer(ctx context.Context, id int64) (Reviewer, error) {
	row := q.db.QueryRowContext(ctx, getReviewer, id)
	var i Reviewer
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.Username,
		&i.Active,
		&i.LastAssigned,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewerByDiscordID = `-- name: GetReviewerByDiscordID :one
SELECT id, discord_user_id, username, active, last_assigned, created_at FROM reviewers WHERE discord_user_id = ?
`

func (q *Queries) GetReviewerByDiscordID(ctx context.Context, discordUserID string) (Reviewer, error) {
	row := q.db.QueryRowContext(ctx, getReviewerByDiscordID, discordUserID)
	var i Reviewer
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.Username,
		&i.Active,
		&i.LastAssigned,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveReviewers = `-- name: ListActiveReviewers :many
SELECT id, discord_user_id, username, active, last_assigned, created_at FROM reviewers WHERE active = 1
`

func (q *Queries) ListActiveReviewers(ctx context.Context) ([]Reviewer, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReviewers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reviewer
	for rows.Next() {
		var i Reviewer
		if err := rows.Scan(
			&i.ID,
			&i.DiscordUserID,
			&i.Username,
			&i.Active,
			&i.LastAssigned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReviewers = `-- name: ListAllReviewers :many
SELECT id, discord_user_id, username, active, last_assigned, created_at FROM reviewers
`

func (q *Queries) ListAllReviewers(ctx context.Context) ([]Reviewer, error) {
	rows, err := q.db.QueryContext(ctx, listAllReviewers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reviewer
	for rows.Next() {
		var i Reviewer
		if err := rows.Scan(
			&i.ID,
			&i.DiscordUserID,
			&i.Username,
			&i.Active,
			&i.LastAssigned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewerAssigned = `-- name: UpdateReviewerAssigned :exec
UPDATE reviewers SET last_assigned = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateReviewerAssigned(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateReviewerAssigned, id)
	return err
}
