// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const cancelReviewJob = `-- name: CancelReviewJob :exec
UPDATE review_jobs SET status = 'cancelled' WHERE id = ?
`

func (q *Queries) CancelReviewJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelReviewJob, id)
	return err
}

const listPendingJobsByReviewer = `-- name: ListPendingJobsByReviewer :many
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs WHERE reviewer_id = ? AND status = 'pending'
ORDER BY assigned_at ASC
`

func (q *Queries) ListPendingJobsByReviewer(ctx context.Context, reviewerID int64) ([]ReviewJob, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobsByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewJob
	for rows.Next() {
		var i ReviewJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ReviewerID,
			&i.Status,
			&i.AssignedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.MessageID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeReviewJob = `-- name: CompleteReviewJob :exec
UPDATE review_jobs
SET status = 'completed', completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CompleteReviewJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeReviewJob, id)
	return err
}

const completeReviewJobKO = `-- name: CompleteReviewJobKO :exec
UPDATE review_jobs SET status = 'ko', notes = ?, completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

type CompleteReviewJobKOParams struct {
	Notes sql.NullString
	ID    int64
}

func (q *Queries) CompleteReviewJobKO(ctx context.Context, arg CompleteReviewJobKOParams) error {
	_, err := q.db.ExecContext(ctx, completeReviewJobKO, arg.Notes, arg.ID)
	return err
}

const createReviewJob = `-- name: CreateReviewJob :exec
INSERT INTO review_jobs (document_id, reviewer_id, expires_at)
VALUES (?, ?, ?)
`

type CreateReviewJobParams struct {
	DocumentID int64
	ReviewerID int64
	ExpiresAt  sql.NullTime
}

func (q *Queries) CreateReviewJob(ctx context.Context, arg CreateReviewJobParams) error {
	_, err := q.db.ExecContext(ctx, createReviewJob, arg.DocumentID, arg.ReviewerID, arg.ExpiresAt)
	return err
}

const deleteReviewJobsByDocument = `-- name: DeleteReviewJobsByDocument :exec
DELETE FROM review_jobs WHERE document_id = ?
`

func (q *Queries) DeleteReviewJobsByDocument(ctx context.Context, documentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReviewJobsByDocument, documentID)
	return err
}

const expireReviewJob = `-- name: ExpireReviewJob :exec
UPDATE review_jobs SET status = 'expired' WHERE id = ?
`

func (q *Queries) ExpireReviewJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, expireReviewJob, id)
	return err
}

const getLatestKOJobForDocument = `-- name: GetLatestKOJobForDocument :one
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs
WHERE document_id = ? AND status = 'ko'
ORDER BY completed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestKOJobForDocument(ctx context.Context, documentID int64) (ReviewJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestKOJobForDocument, documentID)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ReviewerID,
		&i.Status,
		&i.AssignedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.MessageID,
		&i.Notes,
	)
	return i, err
}

const getPendingJobForDocument = `-- name: GetPendingJobForDocument :one
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs
WHERE document_id = ? AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingJobForDocument(ctx context.Context, documentID int64) (ReviewJob, error) {
	row := q.db.QueryRowContext(ctx, getPendingJobForDocument, documentID)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ReviewerID,
		&i.Status,
		&i.AssignedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.MessageID,
		&i.Notes,
	)
	return i, err
}

const getReviewJob = `-- name: GetReviewJob :one
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs WHERE id = ?
`

func (q *Queries) GetReviewJob(ctx context.Context, id int64) (ReviewJob, error) {
	row := q.db.QueryRowContext(ctx, getReviewJob, id)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ReviewerID,
		&i.Status,
		&i.AssignedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.MessageID,
		&i.Notes,
	)
	return i, err
}

const listJobsByReviewer = `-- name: ListJobsByReviewer :many
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs WHERE reviewer_id = ?
ORDER BY assigned_at DESC
`

func (q *Queries) ListJobsByReviewer(ctx context.Context, reviewerID int64) ([]ReviewJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewJob
	for rows.Next() {
		var i ReviewJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ReviewerID,
			&i.Status,
			&i.AssignedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.MessageID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKOJobs = `-- name: ListKOJobs :many
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs WHERE status = 'ko'
`

func (q *Queries) ListKOJobs(ctx context.Context) ([]ReviewJob, error) {
	rows, err := q.db.QueryContext(ctx, listKOJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewJob
	for rows.Next() {
		var i ReviewJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ReviewerID,
			&i.Status,
			&i.AssignedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.MessageID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT id, document_id, reviewer_id, status, assigned_at, completed_at, expires_at, message_id, notes FROM review_jobs WHERE status = 'pending'
`

func (q *Queries) ListPendingJobs(ctx context.Context) ([]ReviewJob, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewJob
	for rows.Next() {
		var i ReviewJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ReviewerID,
			&i.Status,
			&i.AssignedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.MessageID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobMessageID = `-- name: SetJobMessageID :exec
UPDATE review_jobs SET message_id = ? WHERE id = ?
`

type SetJobMessageIDParams struct {
	MessageID sql.NullString
	ID        int64
}

func (q *Queries) SetJobMessageID(ctx context.Context, arg SetJobMessageIDParams) error {
	_, err := q.db.ExecContext(ctx, setJobMessageID, arg.MessageID, arg.ID)
	return err
}

const skipReviewJob = `-- name: SkipReviewJob :exec
UPDATE review_jobs SET status = 'skipped' WHERE id = ?
`

func (q *Queries) SkipReviewJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, skipReviewJob, id)
	return err
}
